model:
  output_dir: /home/adrian/PROJECTS/HPLC_RT_PRED/models/extra_trees
  model_name: extra_trees_rdkit_pipeline_2026_06_29_v0.pkl
hyperparameters:
  fp_transformer__fp_type: rdkit
  fp_transformer__radius: 3
  fp_transformer__fp_size: 1024
  fp_transformer__dense: true
  fp_transformer__counts: true
  variance_thres__threshold: 0.0
  etr__n_estimators: 500
  etr__max_depth: 300
  etr__max_features: 0.5
  etr__n_jobs: null
  etr__random_state: 123456
datasets:
  train:
    X_path: /home/adrian/PROJECTS/HPLC_RT_PRED/data/processed/X_train_set_retained.npy
    y_path: /home/adrian/PROJECTS/HPLC_RT_PRED/data/processed/y_train_set_retained.npy
  validation:
    X_path: /home/adrian/PROJECTS/HPLC_RT_PRED/data/processed/X_val_set_retained.npy
    y_path: /home/adrian/PROJECTS/HPLC_RT_PRED/data/processed/y_val_set_retained.npy
  test:
    X_path: /home/adrian/PROJECTS/HPLC_RT_PRED/data/processed/X_test_set_retained.npy
    y_path: /home/adrian/PROJECTS/HPLC_RT_PRED/data/processed/y_test_set_retained.npy
metrics:
  train:
    r**2: !!python/object/apply:numpy._core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      3UzasXni7z8=
    mae: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      JSLY9vTx9z8=
    mse: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      xRwRk0WSW0A=
    rmse: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      VlfLiN0AJUA=
  validation:
    r**2: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      Z4H7idbe6D8=
    mae: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      sWAF/E5zSkA=
    mse: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      2o6Y4D2eukA=
    rmse: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      2CfSURmjVEA=
